---
title: "ITS: Dog Skin Microbiome Sequencing QC Report"
author: "Spencer Toth"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    theme: flatly
    highlight: tango
    code_folding: show
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE,
                      fig.width = 12, 
                      fig.height = 8,
                      dpi = 300)

# Load libraries
library(ggplot2)
library(dplyr)
library(tidyr)
library(patchwork)
library(gridExtra)
library(knitr)
library(kableExtra)
library(RColorBrewer)
library(scales)
library(purrr)
library(cowplot)
```

## Read-Dropout QC
```{r summary-table-individual, echo=TRUE}

# Load and combine all data SAFELY
all_data <- read.csv("../01_input_files/csv_files/seqruns_final_summary_read_counts.csv")
sample_metadata_og <- read.delim("../../metadata/01_input_files/CH-All_ITS_Metadata_20220124.tsv", header=TRUE)


all_data <- all_data %>% 
  rename(
    Sample      = sample,
    Individual = Individual,
    Total_Reads    = Raw_Sum,
    No_Ns = No_Ns_Sum,
    No_Primers = No_Primers_Sum,
    Filtered_reads  = Trimmed_Sum,
    denoised_forward = denoised_reads,
    No_Chimeras = chimeras_removed_reads,
    Canine_ID      = Dog_ID,
    Sample_Site    = Sample_Site,
    Category       = Collection_Cat,
    Surgery        = Surgery_Type
  ) 

all_data <- all_data %>%
  mutate(
    Sample = factor(Sample, levels = Sample[order(Total_Reads)])
  )

ggplot(all_data, aes(x = Total_Reads, y = Filtered_reads)) +
  geom_point(size = 2.5, alpha = 0.8, color = "#2C7FB8") +
  scale_y_continuous(labels = comma) +
  labs(
    x = "Total_Reads",
    y = "Filtered reads",
    title = "Trimmed reads per sample"
  ) +
  theme_classic() +
  theme(
    axis.text.y = element_text(size = 7),
    plot.title = element_text(face = "bold")
  )


dog_totals <- all_data %>%
  group_by(Individual) %>%
  summarise(
    Total_Reads_Dog = sum(Total_Reads, na.rm = TRUE),
    Removed_Ns_Dog = sum(No_Ns, na.rm = TRUE),
    Remove_Primers_Dog = sum(No_Primers, na.rm = TRUE),
    Filtered_Reads_Dog = sum(Filtered_reads, na.rm = TRUE),
    Final_Reads_Dog = sum(No_Chimeras, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  arrange(Total_Reads_Dog)

dog_totals$Individual <- factor(dog_totals$Individual, levels = dog_totals$Individual)

ggplot(dog_totals, aes(x = Individual)) +
  geom_col(aes(y = Total_Reads_Dog), fill = "#CC00CC", alpha = 1) +
  geom_col(aes(y = Removed_Ns_Dog), fill = "pink", alpha = 1) +
  geom_col(aes(y = Remove_Primers_Dog), fill = "purple", alpha = 1) +
  geom_col(aes(y = Filtered_Reads_Dog), fill = "#1b9e77", alpha = 1) +
  geom_col(aes(y = Final_Reads_Dog), fill = "#FF9900", alpha = 1) +
  theme_classic() +
  labs(
    x = "Individual",
    y = "Reads",
    title = "Total Reads and Final Reads per Individual",
    subtitle = "Ordered from lowest to highest total reads"
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


all_data <- all_data %>%
  left_join(
    sample_metadata_og %>% dplyr::select(Sample_Unique, Sample_Plate), 
    by = c("Sample" = "Sample_Unique")
  )
 

summary_by_run <- all_data %>%
  group_by(Sample_Plate) %>%
  summarise(
    N_Samples = n(),
    Tot_Raw      = sum(Total_Reads, na.rm = TRUE),
    Tot_Removed_Ns_Dog = sum(No_Ns, na.rm = TRUE),
    Tot_Remove_Primers_Dog = sum(No_Primers, na.rm = TRUE),
    Tot_Trimmed  = sum(Filtered_reads, na.rm = TRUE),
    Tot_F_Denois = sum(denoised_forward, na.rm = TRUE),
    Tot_NoChim   = sum(No_Chimeras, na.rm = TRUE),
    
    
    mean_Raw      = mean(Total_Reads, na.rm = TRUE)/1000,
    mean_Removed_Ns_Dog = mean(No_Ns, na.rm = TRUE)/1000,
    mean_Remove_Primers_Dog = mean(No_Primers, na.rm = TRUE)/1000,
    mean_Trimmed  = mean(Filtered_reads, na.rm = TRUE)/1000,
    mean_F_Denois = mean(denoised_forward, na.rm = TRUE)/1000,
    mean_NoChim   = mean(No_Chimeras, na.rm = TRUE)/1000,
    
    
    Ns_Read_Loss_Pct          = round((Tot_Raw - Tot_Removed_Ns_Dog) / Tot_Raw * 100, 1),
    Primers_Read_Loss_Pct          = round((Tot_Removed_Ns_Dog - Tot_Remove_Primers_Dog) / Tot_Removed_Ns_Dog * 100, 1),
    Trimmed_Read_Loss_Pct          = round((Tot_Remove_Primers_Dog - Tot_Trimmed) / Tot_Remove_Primers_Dog * 100, 1),
    Forward_Denoised_Read_Loss_Pct = round((Tot_Trimmed - Tot_F_Denois) / Tot_Trimmed * 100, 1),
    Chimeras_Read_Loss_Pct         = round((Tot_F_Denois - Tot_NoChim) / Tot_F_Denois * 100, 1),
    
    .groups = "drop"
  ) %>%
  dplyr::select(
    Sample_Plate,
    N_Samples,
    mean_Raw,
    mean_Removed_Ns_Dog,
    mean_Remove_Primers_Dog,
    mean_Trimmed,
    mean_F_Denois,
    mean_NoChim,
    Ns_Read_Loss_Pct,
    Primers_Read_Loss_Pct,
    Trimmed_Read_Loss_Pct,
    Forward_Denoised_Read_Loss_Pct,
    Chimeras_Read_Loss_Pct
  ) %>%
  arrange(Sample_Plate)

 
 
kable(
  summary_by_run,
  caption = "Summary Statistics by Seq Run",
  digits = 2,
  col.names = c(
  "Seq. Run",
  "N Samples",
  "Total Fwd Reads",
  "Total Fwd Reads (No Ns)",
  "Primers-Removed",
  "Filtered Reads",
  "Denoised Fwd",
  "Chimeras-removed",
  "Ns removed Read Loss (%)",
  "Primers removed Read Loss (%)",
  "Filtered Read Loss (%)",
  "Denoised Fwd Read Loss (%)",
  "Chimera Removal Read Loss (%)"
)
) %>%
  add_header_above(c(
    " " = 2,
    "Read Average (k)" = 6,
    "Read % Loss at Each Processing Step" = 5
  )) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed")) %>%
  column_spec(1, bold = TRUE, background = "lightgray") %>%
  column_spec(2, border_right = TRUE) %>%
  column_spec(8, border_right = TRUE)
```

## % Read Loss per Sample  
```{r sample-plots-read-loss, fig.height=15, fig.width=12, echo=TRUE}
cat_order <- c(
  "Ns_Read_Loss_Pct",
  "Primers_Read_Loss_Pct",
 "Trimmed_Read_Loss_Pct",
  "Forward_Denoised_Read_Loss_Pct",
  "Chimeras_Read_Loss_Pct"
)

 

label_map <- c(
    "Ns_Read_Loss_Pct"  = "N-removal % Loss",
  "Primers_Read_Loss_Pct"  = "Primer-removal % Loss",
  "Trimmed_Read_Loss_Pct" = "filtAndTrim % Loss",
  "Forward_Denoised_Read_Loss_Pct" = "Fwd Denoised % Lost",
  "Chimeras_Read_Loss_Pct" = "Chimeras % Lost"
)

summary_by_sample <- all_data %>%
  group_by(Sample) %>%
  summarise(
    N_Samples = n(),
    Tot_Raw      = sum(Total_Reads, na.rm = TRUE),
    Tot_Removed_Ns_Dog = sum(No_Ns, na.rm = TRUE),
    Tot_Remove_Primers_Dog = sum(No_Primers, na.rm = TRUE),
    Tot_Trimmed  = sum(Filtered_reads, na.rm = TRUE),
    Tot_F_Denois = sum(denoised_forward, na.rm = TRUE),
    Tot_NoChim   = sum(No_Chimeras, na.rm = TRUE),
    
    
    mean_Raw      = mean(Total_Reads, na.rm = TRUE)/1000,
    mean_Removed_Ns_Dog = mean(No_Ns, na.rm = TRUE)/1000,
    mean_Remove_Primers_Dog = mean(No_Primers, na.rm = TRUE)/1000,
    mean_Trimmed  = mean(Filtered_reads, na.rm = TRUE)/1000,
    mean_F_Denois = mean(denoised_forward, na.rm = TRUE)/1000,
    mean_NoChim   = mean(No_Chimeras, na.rm = TRUE)/1000,
    
    
    Ns_Read_Loss_Pct          = round((Tot_Raw - Tot_Removed_Ns_Dog) / Tot_Raw * 100, 1),
    Primers_Read_Loss_Pct          = round((Tot_Removed_Ns_Dog - Tot_Remove_Primers_Dog) / Tot_Removed_Ns_Dog * 100, 1),
    Trimmed_Read_Loss_Pct          = round((Tot_Remove_Primers_Dog - Tot_Trimmed) / Tot_Remove_Primers_Dog * 100, 1),
    Forward_Denoised_Read_Loss_Pct = round((Tot_Trimmed - Tot_F_Denois) / Tot_Trimmed * 100, 1),
    Chimeras_Read_Loss_Pct         = round((Tot_F_Denois - Tot_NoChim) / Tot_F_Denois * 100, 1),
    
    .groups = "drop"
  ) %>%
  # 4. Remove the temporary total columns used for calculations
  dplyr::select(-starts_with("Tot_"))  

 

plot_data <- summary_by_sample %>%
  pivot_longer(
    cols = all_of(cat_order),
    names_to = "Category",
    values_to = "Read_Loss_Pct"
  ) %>%
  mutate(
    Category = factor(Category, levels = cat_order)
  )

colors <- c(
  "Ns_Read_Loss_Pct" = "pink",
  "Primers_Read_Loss_Pct" = "purple",
  "Trimmed_Read_Loss_Pct" = "#1b9e77",
  "Forward_Denoised_Read_Loss_Pct" = "#FF9900",
  "Chimeras_Read_Loss_Pct" = "#CC00CC"
)
 
summary_df <- plot_data %>%
  group_by(Category) %>%
  summarise(
    mean_val = mean(Read_Loss_Pct, na.rm = TRUE),
    median_val = median(Read_Loss_Pct, na.rm = TRUE),
    min_val = min(Read_Loss_Pct, na.rm = TRUE),
    max_val = max(Read_Loss_Pct, na.rm = TRUE),
    label = paste0(
 #     "n=", n(), "\n",
      "Mean: ", round(mean_val, 1), "%\n",
  #    "Median: ", round(median_val, 1), "%\n",
      "Min: ", round(min_val, 1), "%\n",
      "Max: ", round(max_val, 1), "%"
    ),
    .groups = "drop"
  ) %>%
  mutate(y = 95)

ggplot(plot_data, aes(x = Category, y = Read_Loss_Pct, fill = Category)) +
  geom_boxplot(alpha = 0.8, outlier.shape = NA) +
  geom_label(
    data = summary_df,
    aes(x = Category, y = y, label = label),
    inherit.aes = FALSE,
    size = 5,
    label.size = 0.5,
    fill = "white",
    alpha = 0.9
  ) +
  scale_x_discrete(labels = label_map) +
  scale_fill_manual(values = colors, guide = "none") +
  scale_y_continuous(
    limits = c(0, 100),
    breaks = seq(0, 100, by = 10),
    expand = expansion(mult = c(0, 0.02))
  ) +
  labs(
    x = "Processing Step",
    y = "Read Loss (%)",
    title = "Read Loss by Processing Step Across Samples"
  ) +
  theme_minimal(base_size = 20) +
  theme(
    axis.text.x = element_text(angle = 50, hjust = 1),
    panel.grid.minor = element_blank()
  )
```

## % Read Loss per individual 
```{r individual-plots-read-loss, fig.height=15, fig.width=12, echo=TRUE}
cat_order <- c(
  "Ns_Read_Loss_Pct",
  "Primers_Read_Loss_Pct",
 "Trimmed_Read_Loss_Pct",
  "Forward_Denoised_Read_Loss_Pct",
  "Chimeras_Read_Loss_Pct"
)

 

label_map <- c(
    "Ns_Read_Loss_Pct"  = "N-removal % Loss",
  "Primers_Read_Loss_Pct"  = "Primer-removal % Loss",
  "Trimmed_Read_Loss_Pct" = "filtAndTrim % Loss",
  "Forward_Denoised_Read_Loss_Pct" = "Fwd Denoised % Lost",
  "Chimeras_Read_Loss_Pct" = "Chimeras % Lost"
)

summary_by_sample <- all_data %>%
  group_by(Individual) %>%
  summarise(
    N_Samples = n(),
    Tot_Raw      = sum(Total_Reads, na.rm = TRUE),
    Tot_Removed_Ns_Dog = sum(No_Ns, na.rm = TRUE),
    Tot_Remove_Primers_Dog = sum(No_Primers, na.rm = TRUE),
    Tot_Trimmed  = sum(Filtered_reads, na.rm = TRUE),
    Tot_F_Denois = sum(denoised_forward, na.rm = TRUE),
    Tot_NoChim   = sum(No_Chimeras, na.rm = TRUE),
    
    
    mean_Raw      = mean(Total_Reads, na.rm = TRUE)/1000,
    mean_Removed_Ns_Dog = mean(No_Ns, na.rm = TRUE)/1000,
    mean_Remove_Primers_Dog = mean(No_Primers, na.rm = TRUE)/1000,
    mean_Trimmed  = mean(Filtered_reads, na.rm = TRUE)/1000,
    mean_F_Denois = mean(denoised_forward, na.rm = TRUE)/1000,
    mean_NoChim   = mean(No_Chimeras, na.rm = TRUE)/1000,
    
    
    Ns_Read_Loss_Pct          = round((Tot_Raw - Tot_Removed_Ns_Dog) / Tot_Raw * 100, 1),
    Primers_Read_Loss_Pct          = round((Tot_Removed_Ns_Dog - Tot_Remove_Primers_Dog) / Tot_Removed_Ns_Dog * 100, 1),
    Trimmed_Read_Loss_Pct          = round((Tot_Remove_Primers_Dog - Tot_Trimmed) / Tot_Remove_Primers_Dog * 100, 1),
    Forward_Denoised_Read_Loss_Pct = round((Tot_Trimmed - Tot_F_Denois) / Tot_Trimmed * 100, 1),
    Chimeras_Read_Loss_Pct         = round((Tot_F_Denois - Tot_NoChim) / Tot_F_Denois * 100, 1),
    
    .groups = "drop"
  ) %>%
  # 4. Remove the temporary total columns used for calculations
  dplyr::select(-starts_with("Tot_"))  

 

plot_data <- summary_by_sample %>%
  pivot_longer(
    cols = all_of(cat_order),
    names_to = "Category",
    values_to = "Read_Loss_Pct"
  ) %>%
  mutate(
    Category = factor(Category, levels = cat_order)
  )

colors <- c(
  "Ns_Read_Loss_Pct" = "pink",
  "Primers_Read_Loss_Pct" = "purple",
  "Trimmed_Read_Loss_Pct" = "#1b9e77",
  "Forward_Denoised_Read_Loss_Pct" = "#FF9900",
  "Chimeras_Read_Loss_Pct" = "#CC00CC"
)

 
summary_df <- plot_data %>%
  group_by(Category) %>%
  summarise(
    mean_val = mean(Read_Loss_Pct, na.rm = TRUE),
    median_val = median(Read_Loss_Pct, na.rm = TRUE),
    min_val = min(Read_Loss_Pct, na.rm = TRUE),
    max_val = max(Read_Loss_Pct, na.rm = TRUE),
    label = paste0(
 #     "n=", n(), "\n",
      "Mean: ", round(mean_val, 1), "%\n",
  #    "Median: ", round(median_val, 1), "%\n",
      "Min: ", round(min_val, 1), "%\n",
      "Max: ", round(max_val, 1), "%"
    ),
    .groups = "drop"
  ) %>%
  mutate(y = 75)

ggplot(plot_data, aes(x = Category, y = Read_Loss_Pct, fill = Category)) +
  geom_boxplot(alpha = 0.8, outlier.shape = NA) +
  geom_label(
    data = summary_df,
    aes(x = Category, y = y, label = label),
    inherit.aes = FALSE,
    size = 5,
    label.size = 0.5,
    fill = "white",
    alpha = 0.9
  ) +
  scale_x_discrete(labels = label_map) +
  scale_fill_manual(values = colors, guide = "none") +
  scale_y_continuous(
    limits = c(0, 100),
    breaks = seq(0, 100, by = 10),
    expand = expansion(mult = c(0, 0.02))
  ) +
  labs(
    x = "Processing Step",
    y = "Read Loss (%)",
    title = "Read Loss by Processing Step Across Individuals"
  ) +
  theme_minimal(base_size = 20) +
  theme(
    axis.text.x = element_text(angle = 50, hjust = 1),
    panel.grid.minor = element_blank()
  )
```

 
**Session Info:**
```{r session-info, echo=FALSE}
sessionInfo()
```

---

